/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TramitesRouteImport } from './routes/tramites'
import { Route as PlataformasRouteImport } from './routes/plataformas'
import { Route as OficinaEducativaRouteImport } from './routes/oficinaEducativa'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComunicadosRouteImport } from './routes/comunicados'
import { Route as CarrerasRouteImport } from './routes/carreras'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OficinaEducativaIndexRouteImport } from './routes/oficinaEducativa/index'
import { Route as OficinaEducativaRecursosDocentesRouteImport } from './routes/oficinaEducativa/recursos-docentes'
import { Route as OficinaEducativaJornadasRouteImport } from './routes/oficinaEducativa/jornadas'
import { Route as OficinaEducativaCuadroHonorRouteImport } from './routes/oficinaEducativa/cuadro-honor'
import { Route as OficinaEducativaAuxiliaresRouteImport } from './routes/oficinaEducativa/auxiliares'
import { Route as OficinaEducativaAdmisionesRouteImport } from './routes/oficinaEducativa/admisiones'
import { Route as CarrerasCareerRouteImport } from './routes/carreras.$career'

const TramitesRoute = TramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformasRoute = PlataformasRouteImport.update({
  id: '/plataformas',
  path: '/plataformas',
  getParentRoute: () => rootRouteImport,
} as any)
const OficinaEducativaRoute = OficinaEducativaRouteImport.update({
  id: '/oficinaEducativa',
  path: '/oficinaEducativa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicadosRoute = ComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRoute = CarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OficinaEducativaIndexRoute = OficinaEducativaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OficinaEducativaRoute,
} as any)
const OficinaEducativaRecursosDocentesRoute =
  OficinaEducativaRecursosDocentesRouteImport.update({
    id: '/recursos-docentes',
    path: '/recursos-docentes',
    getParentRoute: () => OficinaEducativaRoute,
  } as any)
const OficinaEducativaJornadasRoute =
  OficinaEducativaJornadasRouteImport.update({
    id: '/jornadas',
    path: '/jornadas',
    getParentRoute: () => OficinaEducativaRoute,
  } as any)
const OficinaEducativaCuadroHonorRoute =
  OficinaEducativaCuadroHonorRouteImport.update({
    id: '/cuadro-honor',
    path: '/cuadro-honor',
    getParentRoute: () => OficinaEducativaRoute,
  } as any)
const OficinaEducativaAuxiliaresRoute =
  OficinaEducativaAuxiliaresRouteImport.update({
    id: '/auxiliares',
    path: '/auxiliares',
    getParentRoute: () => OficinaEducativaRoute,
  } as any)
const OficinaEducativaAdmisionesRoute =
  OficinaEducativaAdmisionesRouteImport.update({
    id: '/admisiones',
    path: '/admisiones',
    getParentRoute: () => OficinaEducativaRoute,
  } as any)
const CarrerasCareerRoute = CarrerasCareerRouteImport.update({
  id: '/$career',
  path: '/$career',
  getParentRoute: () => CarrerasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/comunicados': typeof ComunicadosRoute
  '/contacto': typeof ContactoRoute
  '/oficinaEducativa': typeof OficinaEducativaRouteWithChildren
  '/plataformas': typeof PlataformasRoute
  '/tramites': typeof TramitesRoute
  '/carreras/$career': typeof CarrerasCareerRoute
  '/oficinaEducativa/admisiones': typeof OficinaEducativaAdmisionesRoute
  '/oficinaEducativa/auxiliares': typeof OficinaEducativaAuxiliaresRoute
  '/oficinaEducativa/cuadro-honor': typeof OficinaEducativaCuadroHonorRoute
  '/oficinaEducativa/jornadas': typeof OficinaEducativaJornadasRoute
  '/oficinaEducativa/recursos-docentes': typeof OficinaEducativaRecursosDocentesRoute
  '/oficinaEducativa/': typeof OficinaEducativaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/comunicados': typeof ComunicadosRoute
  '/contacto': typeof ContactoRoute
  '/plataformas': typeof PlataformasRoute
  '/tramites': typeof TramitesRoute
  '/carreras/$career': typeof CarrerasCareerRoute
  '/oficinaEducativa/admisiones': typeof OficinaEducativaAdmisionesRoute
  '/oficinaEducativa/auxiliares': typeof OficinaEducativaAuxiliaresRoute
  '/oficinaEducativa/cuadro-honor': typeof OficinaEducativaCuadroHonorRoute
  '/oficinaEducativa/jornadas': typeof OficinaEducativaJornadasRoute
  '/oficinaEducativa/recursos-docentes': typeof OficinaEducativaRecursosDocentesRoute
  '/oficinaEducativa': typeof OficinaEducativaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/comunicados': typeof ComunicadosRoute
  '/contacto': typeof ContactoRoute
  '/oficinaEducativa': typeof OficinaEducativaRouteWithChildren
  '/plataformas': typeof PlataformasRoute
  '/tramites': typeof TramitesRoute
  '/carreras/$career': typeof CarrerasCareerRoute
  '/oficinaEducativa/admisiones': typeof OficinaEducativaAdmisionesRoute
  '/oficinaEducativa/auxiliares': typeof OficinaEducativaAuxiliaresRoute
  '/oficinaEducativa/cuadro-honor': typeof OficinaEducativaCuadroHonorRoute
  '/oficinaEducativa/jornadas': typeof OficinaEducativaJornadasRoute
  '/oficinaEducativa/recursos-docentes': typeof OficinaEducativaRecursosDocentesRoute
  '/oficinaEducativa/': typeof OficinaEducativaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/carreras'
    | '/comunicados'
    | '/contacto'
    | '/oficinaEducativa'
    | '/plataformas'
    | '/tramites'
    | '/carreras/$career'
    | '/oficinaEducativa/admisiones'
    | '/oficinaEducativa/auxiliares'
    | '/oficinaEducativa/cuadro-honor'
    | '/oficinaEducativa/jornadas'
    | '/oficinaEducativa/recursos-docentes'
    | '/oficinaEducativa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/carreras'
    | '/comunicados'
    | '/contacto'
    | '/plataformas'
    | '/tramites'
    | '/carreras/$career'
    | '/oficinaEducativa/admisiones'
    | '/oficinaEducativa/auxiliares'
    | '/oficinaEducativa/cuadro-honor'
    | '/oficinaEducativa/jornadas'
    | '/oficinaEducativa/recursos-docentes'
    | '/oficinaEducativa'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/carreras'
    | '/comunicados'
    | '/contacto'
    | '/oficinaEducativa'
    | '/plataformas'
    | '/tramites'
    | '/carreras/$career'
    | '/oficinaEducativa/admisiones'
    | '/oficinaEducativa/auxiliares'
    | '/oficinaEducativa/cuadro-honor'
    | '/oficinaEducativa/jornadas'
    | '/oficinaEducativa/recursos-docentes'
    | '/oficinaEducativa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CarrerasRoute: typeof CarrerasRouteWithChildren
  ComunicadosRoute: typeof ComunicadosRoute
  ContactoRoute: typeof ContactoRoute
  OficinaEducativaRoute: typeof OficinaEducativaRouteWithChildren
  PlataformasRoute: typeof PlataformasRoute
  TramitesRoute: typeof TramitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tramites': {
      id: '/tramites'
      path: '/tramites'
      fullPath: '/tramites'
      preLoaderRoute: typeof TramitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataformas': {
      id: '/plataformas'
      path: '/plataformas'
      fullPath: '/plataformas'
      preLoaderRoute: typeof PlataformasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficinaEducativa': {
      id: '/oficinaEducativa'
      path: '/oficinaEducativa'
      fullPath: '/oficinaEducativa'
      preLoaderRoute: typeof OficinaEducativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicados': {
      id: '/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras': {
      id: '/carreras'
      path: '/carreras'
      fullPath: '/carreras'
      preLoaderRoute: typeof CarrerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficinaEducativa/': {
      id: '/oficinaEducativa/'
      path: '/'
      fullPath: '/oficinaEducativa/'
      preLoaderRoute: typeof OficinaEducativaIndexRouteImport
      parentRoute: typeof OficinaEducativaRoute
    }
    '/oficinaEducativa/recursos-docentes': {
      id: '/oficinaEducativa/recursos-docentes'
      path: '/recursos-docentes'
      fullPath: '/oficinaEducativa/recursos-docentes'
      preLoaderRoute: typeof OficinaEducativaRecursosDocentesRouteImport
      parentRoute: typeof OficinaEducativaRoute
    }
    '/oficinaEducativa/jornadas': {
      id: '/oficinaEducativa/jornadas'
      path: '/jornadas'
      fullPath: '/oficinaEducativa/jornadas'
      preLoaderRoute: typeof OficinaEducativaJornadasRouteImport
      parentRoute: typeof OficinaEducativaRoute
    }
    '/oficinaEducativa/cuadro-honor': {
      id: '/oficinaEducativa/cuadro-honor'
      path: '/cuadro-honor'
      fullPath: '/oficinaEducativa/cuadro-honor'
      preLoaderRoute: typeof OficinaEducativaCuadroHonorRouteImport
      parentRoute: typeof OficinaEducativaRoute
    }
    '/oficinaEducativa/auxiliares': {
      id: '/oficinaEducativa/auxiliares'
      path: '/auxiliares'
      fullPath: '/oficinaEducativa/auxiliares'
      preLoaderRoute: typeof OficinaEducativaAuxiliaresRouteImport
      parentRoute: typeof OficinaEducativaRoute
    }
    '/oficinaEducativa/admisiones': {
      id: '/oficinaEducativa/admisiones'
      path: '/admisiones'
      fullPath: '/oficinaEducativa/admisiones'
      preLoaderRoute: typeof OficinaEducativaAdmisionesRouteImport
      parentRoute: typeof OficinaEducativaRoute
    }
    '/carreras/$career': {
      id: '/carreras/$career'
      path: '/$career'
      fullPath: '/carreras/$career'
      preLoaderRoute: typeof CarrerasCareerRouteImport
      parentRoute: typeof CarrerasRoute
    }
  }
}

interface CarrerasRouteChildren {
  CarrerasCareerRoute: typeof CarrerasCareerRoute
}

const CarrerasRouteChildren: CarrerasRouteChildren = {
  CarrerasCareerRoute: CarrerasCareerRoute,
}

const CarrerasRouteWithChildren = CarrerasRoute._addFileChildren(
  CarrerasRouteChildren,
)

interface OficinaEducativaRouteChildren {
  OficinaEducativaAdmisionesRoute: typeof OficinaEducativaAdmisionesRoute
  OficinaEducativaAuxiliaresRoute: typeof OficinaEducativaAuxiliaresRoute
  OficinaEducativaCuadroHonorRoute: typeof OficinaEducativaCuadroHonorRoute
  OficinaEducativaJornadasRoute: typeof OficinaEducativaJornadasRoute
  OficinaEducativaRecursosDocentesRoute: typeof OficinaEducativaRecursosDocentesRoute
  OficinaEducativaIndexRoute: typeof OficinaEducativaIndexRoute
}

const OficinaEducativaRouteChildren: OficinaEducativaRouteChildren = {
  OficinaEducativaAdmisionesRoute: OficinaEducativaAdmisionesRoute,
  OficinaEducativaAuxiliaresRoute: OficinaEducativaAuxiliaresRoute,
  OficinaEducativaCuadroHonorRoute: OficinaEducativaCuadroHonorRoute,
  OficinaEducativaJornadasRoute: OficinaEducativaJornadasRoute,
  OficinaEducativaRecursosDocentesRoute: OficinaEducativaRecursosDocentesRoute,
  OficinaEducativaIndexRoute: OficinaEducativaIndexRoute,
}

const OficinaEducativaRouteWithChildren =
  OficinaEducativaRoute._addFileChildren(OficinaEducativaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CarrerasRoute: CarrerasRouteWithChildren,
  ComunicadosRoute: ComunicadosRoute,
  ContactoRoute: ContactoRoute,
  OficinaEducativaRoute: OficinaEducativaRouteWithChildren,
  PlataformasRoute: PlataformasRoute,
  TramitesRoute: TramitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
